---
- name: configure/worker - copy tsa public key
  copy:
    content: "{{ concourse_tsa_public_key }}"
    dest: "{{ concourse_tsa_public_key_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: yes
  notify:
    - restart concourse worker
  when: concourse_tsa_public_key is defined and concourse_tsa_public_key|length

- name: configure/worker - copy worker key
  copy:
    content: "{{ concourse_tsa_worker_key }}"
    dest: "{{ concourse_tsa_worker_key_path }}"
    owner: "{{ concourse_user }}"
    group: "{{ concourse_group }}"
    mode: "{{ concourse_etc_files_mode }}"
  become: yes
  notify:
    - restart concourse worker
  when: concourse_tsa_worker_key is defined and concourse_tsa_worker_key|length
