---

- import_tasks: user.yml
  when: concourse_manage_user

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: start.yml

- shell: /bin/true
  when: concourse_force_restart
  notify:
  - restart concourse web
  - restart concourse worker
